"""
DSO Catalog for ZWO Seestar S50
Objects optimized for the Seestar S50's 50mm aperture and 250mm focal length.
"""

from astropy.coordinates import SkyCoord
import astropy.units as u

# Each entry: name, messier_id, ra, dec, type, magnitude, size_arcmin,
#             constellation, best_months, seestar_rating (1-5),
#             filter_type, notes
DSO_CATALOG = [
    # ── EMISSION NEBULAE ──────────────────────────────────────────────────────
    {
        "name": "Orion Nebula",
        "messier_id": "M42",
        "ra": "05h35m17.3s",
        "dec": "-05d23m28s",
        "type": "Emission Nebula",
        "magnitude": 4.0,
        "size_arcmin": 85,
        "constellation": "Orion",
        "best_months": [11, 12, 1, 2, 3],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Showpiece nebula. Stunning structure and colors. Use dual-band filter for best results.",
    },
    {
        "name": "De Mairan's Nebula",
        "messier_id": "M43",
        "ra": "05h35m31s",
        "dec": "-05d16m3s",
        "type": "Emission Nebula",
        "magnitude": 9.0,
        "size_arcmin": 20,
        "constellation": "Orion",
        "best_months": [11, 12, 1, 2, 3],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Companion to M42. Often imaged together in the same field.",
    },
    {
        "name": "Lagoon Nebula",
        "messier_id": "M8",
        "ra": "18h03m37s",
        "dec": "-24d23m12s",
        "type": "Emission Nebula",
        "magnitude": 6.0,
        "size_arcmin": 90,
        "constellation": "Sagittarius",
        "best_months": [6, 7, 8, 9],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Large, bright nebula with embedded star cluster. Summer showpiece.",
    },
    {
        "name": "Trifid Nebula",
        "messier_id": "M20",
        "ra": "18h02m42s",
        "dec": "-23d01m48s",
        "type": "Emission Nebula",
        "magnitude": 8.5,
        "size_arcmin": 28,
        "constellation": "Sagittarius",
        "best_months": [6, 7, 8, 9],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Three-lobed structure. Mix of emission and reflection nebulosity.",
    },
    {
        "name": "Omega/Swan Nebula",
        "messier_id": "M17",
        "ra": "18h20m26s",
        "dec": "-16d10m36s",
        "type": "Emission Nebula",
        "magnitude": 6.0,
        "size_arcmin": 46,
        "constellation": "Sagittarius",
        "best_months": [6, 7, 8, 9],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "One of the brightest nebulae. Distinctive swan shape. Responds well to H-alpha.",
    },
    {
        "name": "Eagle Nebula",
        "messier_id": "M16",
        "ra": "18h18m48s",
        "dec": "-13d47m24s",
        "type": "Emission Nebula",
        "magnitude": 6.4,
        "size_arcmin": 35,
        "constellation": "Serpens",
        "best_months": [6, 7, 8, 9],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Home of the Pillars of Creation. Dual-band filter reveals fine structure.",
    },
    {
        "name": "Crab Nebula",
        "messier_id": "M1",
        "ra": "05h34m31.94s",
        "dec": "+22d00m52.2s",
        "type": "Supernova Remnant",
        "magnitude": 8.4,
        "size_arcmin": 7,
        "constellation": "Taurus",
        "best_months": [12, 1, 2, 3],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Remnant of 1054 AD supernova. Small but interesting filamentary structure.",
    },
    {
        "name": "Ring Nebula",
        "messier_id": "M57",
        "ra": "18h53m35.08s",
        "dec": "+33d01m44.9s",
        "type": "Planetary Nebula",
        "magnitude": 8.8,
        "size_arcmin": 3,
        "constellation": "Lyra",
        "best_months": [6, 7, 8, 9],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Classic planetary nebula. Stunning ring structure even at small aperture.",
    },
    {
        "name": "Dumbbell Nebula",
        "messier_id": "M27",
        "ra": "19h59m36.34s",
        "dec": "+22d43m16.1s",
        "type": "Planetary Nebula",
        "magnitude": 7.5,
        "size_arcmin": 8,
        "constellation": "Vulpecula",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Largest and brightest planetary nebula. Apple-core shape visible.",
    },
    {
        "name": "North America Nebula",
        "messier_id": "NGC 7000",
        "ra": "20h59m17s",
        "dec": "+44d31m44s",
        "type": "Emission Nebula",
        "magnitude": 4.0,
        "size_arcmin": 120,
        "constellation": "Cygnus",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Enormous nebula. Dual-band or H-alpha filter essential for detail.",
    },
    {
        "name": "Pelican Nebula",
        "messier_id": "IC 5070",
        "ra": "20h50m48s",
        "dec": "+44d21m00s",
        "type": "Emission Nebula",
        "magnitude": 8.0,
        "size_arcmin": 60,
        "constellation": "Cygnus",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Adjacent to NGC 7000. Images well in the same frame.",
    },
    {
        "name": "Heart Nebula",
        "messier_id": "IC 1805",
        "ra": "02h32m42s",
        "dec": "+61d27m00s",
        "type": "Emission Nebula",
        "magnitude": 6.5,
        "size_arcmin": 60,
        "constellation": "Cassiopeia",
        "best_months": [10, 11, 12, 1, 2],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Circumpolar from Vienna. Heart-shaped H-alpha region.",
    },
    {
        "name": "Soul Nebula",
        "messier_id": "IC 1848",
        "ra": "02h51m12s",
        "dec": "+60d25m00s",
        "type": "Emission Nebula",
        "magnitude": 6.5,
        "size_arcmin": 60,
        "constellation": "Cassiopeia",
        "best_months": [10, 11, 12, 1, 2],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Companion to IC 1805. Heart and Soul together make a striking pair.",
    },
    {
        "name": "Rosette Nebula",
        "messier_id": "NGC 2237",
        "ra": "06h31m54s",
        "dec": "+04d56m00s",
        "type": "Emission Nebula",
        "magnitude": 9.0,
        "size_arcmin": 80,
        "constellation": "Monoceros",
        "best_months": [12, 1, 2, 3],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Large rose-shaped nebula. Dual-band filter transforms this object.",
    },
    {
        "name": "California Nebula",
        "messier_id": "NGC 1499",
        "ra": "04h00m42s",
        "dec": "+36d37m00s",
        "type": "Emission Nebula",
        "magnitude": 6.0,
        "size_arcmin": 145,
        "constellation": "Perseus",
        "best_months": [11, 12, 1, 2],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Very large nebula. Narrowband filter required to see shape.",
    },
    {
        "name": "Horsehead Nebula",
        "messier_id": "IC 434",
        "ra": "05h40m59s",
        "dec": "-02d27m30s",
        "type": "Dark/Emission Nebula",
        "magnitude": 6.8,
        "size_arcmin": 8,
        "constellation": "Orion",
        "best_months": [12, 1, 2, 3],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Dark nebula silhouetted against IC 434. H-alpha filter essential.",
    },
    {
        "name": "Flame Nebula",
        "messier_id": "NGC 2024",
        "ra": "05h41m54s",
        "dec": "-01d51m00s",
        "type": "Emission Nebula",
        "magnitude": 2.0,
        "size_arcmin": 30,
        "constellation": "Orion",
        "best_months": [12, 1, 2, 3],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Bright nebula near Alnitak. Often imaged with Horsehead.",
    },
    {
        "name": "Crescent Nebula",
        "messier_id": "NGC 6888",
        "ra": "20h12m07s",
        "dec": "+38d21m18s",
        "type": "Emission Nebula",
        "magnitude": 7.4,
        "size_arcmin": 18,
        "constellation": "Cygnus",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 4,
        "filter_type": "narrowband",
        "notes": "Wolf-Rayet bubble nebula. Responds very well to narrowband.",
    },
    {
        "name": "Eastern Veil Nebula",
        "messier_id": "NGC 6992",
        "ra": "20h56m24s",
        "dec": "+31d43m00s",
        "type": "Supernova Remnant",
        "magnitude": 7.0,
        "size_arcmin": 60,
        "constellation": "Cygnus",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Bright part of Cygnus Loop. Stunning filamentary structure.",
    },
    {
        "name": "Western Veil Nebula",
        "messier_id": "NGC 6960",
        "ra": "20h45m38s",
        "dec": "+30d42m30s",
        "type": "Supernova Remnant",
        "magnitude": 7.0,
        "size_arcmin": 70,
        "constellation": "Cygnus",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 5,
        "filter_type": "narrowband",
        "notes": "Witch's Broom. Passes through Pickvogel star 52 Cyg. Spectacular.",
    },
    # ── PLANETARY NEBULAE ─────────────────────────────────────────────────────
    {
        "name": "Blue Snowball",
        "messier_id": "NGC 7662",
        "ra": "23h25m54s",
        "dec": "+42d32m6s",
        "type": "Planetary Nebula",
        "magnitude": 8.3,
        "size_arcmin": 0.5,
        "constellation": "Andromeda",
        "best_months": [8, 9, 10, 11],
        "seestar_rating": 3,
        "filter_type": "narrowband",
        "notes": "Compact blue-green disk. Small but high surface brightness.",
    },
    # ── GLOBULAR CLUSTERS ─────────────────────────────────────────────────────
    {
        "name": "Hercules Cluster",
        "messier_id": "M13",
        "ra": "16h41m41.24s",
        "dec": "+36d27m35.5s",
        "type": "Globular Cluster",
        "magnitude": 5.8,
        "size_arcmin": 20,
        "constellation": "Hercules",
        "best_months": [4, 5, 6, 7, 8],
        "seestar_rating": 5,
        "filter_type": "broadband",
        "notes": "Northern sky's finest globular. Partially resolves with Seestar.",
    },
    {
        "name": "M92",
        "messier_id": "M92",
        "ra": "17h17m07.39s",
        "dec": "+43d08m09.4s",
        "type": "Globular Cluster",
        "magnitude": 6.4,
        "size_arcmin": 14,
        "constellation": "Hercules",
        "best_months": [5, 6, 7, 8],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Often overshadowed by M13 but equally impressive.",
    },
    {
        "name": "Great Cluster in Serpens",
        "messier_id": "M5",
        "ra": "15h18m33.22s",
        "dec": "+02d04m51.7s",
        "type": "Globular Cluster",
        "magnitude": 5.6,
        "size_arcmin": 23,
        "constellation": "Serpens",
        "best_months": [4, 5, 6, 7],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "One of the oldest globulars. Rich and well-condensed.",
    },
    {
        "name": "Pegasus Globular",
        "messier_id": "M15",
        "ra": "21h29m58.33s",
        "dec": "+12d10m00.6s",
        "type": "Globular Cluster",
        "magnitude": 6.2,
        "size_arcmin": 18,
        "constellation": "Pegasus",
        "best_months": [7, 8, 9, 10],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Very dense core. One of the most concentrated globulars.",
    },
    {
        "name": "Great Globular in Canes Venatici",
        "messier_id": "M3",
        "ra": "13h42m11.62s",
        "dec": "+28d22m38.2s",
        "type": "Globular Cluster",
        "magnitude": 6.2,
        "size_arcmin": 18,
        "constellation": "Canes Venatici",
        "best_months": [3, 4, 5, 6],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Contains over 500,000 stars. Excellent spring target.",
    },
    # ── OPEN CLUSTERS ─────────────────────────────────────────────────────────
    {
        "name": "Pleiades",
        "messier_id": "M45",
        "ra": "03h47m24s",
        "dec": "+24d07m00s",
        "type": "Open Cluster",
        "magnitude": 1.6,
        "size_arcmin": 110,
        "constellation": "Taurus",
        "best_months": [10, 11, 12, 1, 2],
        "seestar_rating": 5,
        "filter_type": "broadband",
        "notes": "Seven Sisters. Stunning reflection nebulosity surrounds stars.",
    },
    {
        "name": "Double Cluster",
        "messier_id": "NGC 869",
        "ra": "02h19m00s",
        "dec": "+57d07m42s",
        "type": "Open Cluster",
        "magnitude": 4.3,
        "size_arcmin": 30,
        "constellation": "Perseus",
        "best_months": [9, 10, 11, 12, 1],
        "seestar_rating": 5,
        "filter_type": "broadband",
        "notes": "Two clusters (h and chi Per) in one field. Circumpolar showpiece.",
    },
    {
        "name": "Beehive Cluster",
        "messier_id": "M44",
        "ra": "08h40m24s",
        "dec": "+19d40m00s",
        "type": "Open Cluster",
        "magnitude": 3.7,
        "size_arcmin": 95,
        "constellation": "Cancer",
        "best_months": [2, 3, 4, 5],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Large rich cluster. Fills the Seestar's field nicely.",
    },
    {
        "name": "M35",
        "messier_id": "M35",
        "ra": "06h08m54s",
        "dec": "+24d20m00s",
        "type": "Open Cluster",
        "magnitude": 5.1,
        "size_arcmin": 28,
        "constellation": "Gemini",
        "best_months": [12, 1, 2, 3],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Rich cluster with background cluster NGC 2158 visible.",
    },
    {
        "name": "Wild Duck Cluster",
        "messier_id": "M11",
        "ra": "18h51m05s",
        "dec": "-06d16m12s",
        "type": "Open Cluster",
        "magnitude": 5.8,
        "size_arcmin": 14,
        "constellation": "Scutum",
        "best_months": [6, 7, 8, 9],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "One of the richest open clusters. V-shaped flight pattern of stars.",
    },
    # ── GALAXIES ──────────────────────────────────────────────────────────────
    {
        "name": "Andromeda Galaxy",
        "messier_id": "M31",
        "ra": "00h42m44.3s",
        "dec": "+41d16m09s",
        "type": "Galaxy",
        "magnitude": 3.4,
        "size_arcmin": 190,
        "constellation": "Andromeda",
        "best_months": [9, 10, 11, 12],
        "seestar_rating": 5,
        "filter_type": "broadband",
        "notes": "Our nearest large galactic neighbor. Dust lanes and companion galaxies visible.",
    },
    {
        "name": "Bode's Galaxy",
        "messier_id": "M81",
        "ra": "09h55m33.2s",
        "dec": "+69d03m55s",
        "type": "Galaxy",
        "magnitude": 6.9,
        "size_arcmin": 27,
        "constellation": "Ursa Major",
        "best_months": [2, 3, 4, 5],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Grand design spiral. Pairs beautifully with M82 in the same field.",
    },
    {
        "name": "Cigar Galaxy",
        "messier_id": "M82",
        "ra": "09h55m52.2s",
        "dec": "+69d40m47s",
        "type": "Galaxy",
        "magnitude": 8.4,
        "size_arcmin": 11,
        "constellation": "Ursa Major",
        "best_months": [2, 3, 4, 5],
        "seestar_rating": 5,
        "filter_type": "broadband",
        "notes": "Starburst galaxy with dramatic H-alpha outflows. Stunning narrow-band target.",
    },
    {
        "name": "Whirlpool Galaxy",
        "messier_id": "M51",
        "ra": "13h29m52.7s",
        "dec": "+47d11m43s",
        "type": "Galaxy",
        "magnitude": 8.4,
        "size_arcmin": 11,
        "constellation": "Canes Venatici",
        "best_months": [3, 4, 5, 6],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Interacting galaxy pair. Spiral arms visible in longer exposures.",
    },
    {
        "name": "Pinwheel Galaxy",
        "messier_id": "M101",
        "ra": "14h03m12.6s",
        "dec": "+54d20m56s",
        "type": "Galaxy",
        "magnitude": 7.9,
        "size_arcmin": 29,
        "constellation": "Ursa Major",
        "best_months": [4, 5, 6, 7],
        "seestar_rating": 3,
        "filter_type": "broadband",
        "notes": "Face-on spiral. Low surface brightness; needs dark skies.",
    },
    {
        "name": "Triangulum Galaxy",
        "messier_id": "M33",
        "ra": "01h33m50.9s",
        "dec": "+30d39m37s",
        "type": "Galaxy",
        "magnitude": 5.7,
        "size_arcmin": 73,
        "constellation": "Triangulum",
        "best_months": [9, 10, 11, 12],
        "seestar_rating": 4,
        "filter_type": "broadband",
        "notes": "Third-largest Local Group member. Low surface brightness but huge angular size.",
    },
    {
        "name": "Sombrero Galaxy",
        "messier_id": "M104",
        "ra": "12h39m59.4s",
        "dec": "-11d37m23s",
        "type": "Galaxy",
        "magnitude": 8.0,
        "size_arcmin": 9,
        "constellation": "Virgo",
        "best_months": [3, 4, 5, 6],
        "seestar_rating": 3,
        "filter_type": "broadband",
        "notes": "Edge-on galaxy with prominent dust lane. Low altitude from Vienna.",
    },
]


def get_skycoord(obj: dict) -> SkyCoord:
    """Return an astropy SkyCoord for a catalog object."""
    return SkyCoord(ra=obj["ra"], dec=obj["dec"], frame="icrs")


def get_objects_by_type(obj_type: str) -> list:
    """Filter catalog by object type (partial match, case-insensitive)."""
    return [o for o in DSO_CATALOG if obj_type.lower() in o["type"].lower()]


def get_objects_for_month(month: int) -> list:
    """Return objects whose best_months includes the given month."""
    return [o for o in DSO_CATALOG if month in o["best_months"]]


def get_objects_by_filter(filter_type: str) -> list:
    """Return objects that match the given filter type."""
    return [o for o in DSO_CATALOG if o["filter_type"] == filter_type]


TYPE_ICON = {
    "Emission Nebula": "🌌",
    "Planetary Nebula": "🌌",
    "Dark/Emission Nebula": "🌌",
    "Supernova Remnant": "🌌",
    "Globular Cluster": "⭐",
    "Open Cluster": "⭐",
    "Galaxy": "🌀",
}


def type_icon(obj_type: str) -> str:
    """Return an emoji icon for the object type."""
    for key, icon in TYPE_ICON.items():
        if key.lower() in obj_type.lower():
            return icon
    return "✨"


def rating_stars(rating: int) -> str:
    """Return filled/empty star string for seestar_rating."""
    return "★" * rating + "☆" * (5 - rating)
